# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contatinho' do\
  platform :ios, '14.0'
  pod 'EFQRCode'
end

target 'Contatinho WatchKit App' do
  platform :watchos, '7.0'
  pod 'EFQRCode'
end

target 'Contatinho WatchKit Extension' do
  platform :watchos, '7.0'
  pod 'EFQRCode'
end
